Hotel booking/HotelApp/urls.py
#definisem url

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

app_name = 'hotel'

urlpatterns = [
    path('', views.index, name='index'), 
    path('registration', views.registration, name='registration'),
    path('logout', views.logout, name='logout'),
    path('reservation', views.reservation, name='reservation'),
    path('search/', views.search, name='search'),
    path('search/index', views.index, name='index'),
    path('search/search', views.search, name='search'),
    path('search/login', views.login, name='login'),
    path('hotel/login', views.login, name='login'),
    path('hotel/search', views.search, name='search'),
    path('hotel/index', views.index, name='index'),
    
    path('hotel/<int:hotel_id>', views.hotel_details, name='hotel_details'),
   path('hotel/add_comment/<int:hotel_id>/', views.add_comment, name='add_comment'),
    path('hotel/delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +\
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hotel booking/HotelProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HotelApp.urls'))
]

Hotel booking/templates/hotel_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ hotel.ime }} Hotel</title>

    <link rel="stylesheet" href="{% static 'hotel.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>
<body>
    <div class="navbar" id="navbar">
        <a href="index" >Početna</a>
        <a href="search" >Pretraga</a>
        <a href="login">Log in</a>
        <a href="{%static 'javascript:void(0)'%}" class="icon" onclick="toggleNavbar()">
            <i class="fa fa-bars"></i> 
        </a>
    </div>
    
    {% block content %}
    <div class="container">
      <div class="image">
        <img src="{{ hotel.picture.url }}" alt="{{ hotel.ime }}">
      </div>
      <div class="details">
        <h2>{{ hotel.ime }}</h2>
        <p>Zvjezdice: {{ hotel.zvjezdice }} // Mjesto: {{ hotel.mjesto }}</p>

        <form method="post" action="{% url 'hotel:add_comment' hotel.id %}">


            {% csrf_token %}
            
            <div class="comment-section">
              <textarea name="content" placeholder="Napišite recenziju"></textarea>
              <button class="comment-submit" type="submit">Objavi</button>
            </div>
          
        {% for comment in comments %}
        <div class="tekst">
        <div class="comment">
            <h3>Comment ID: {{ comment.id }}<br>
            {{ comment.content }}  //  By: {{ comment.user }}</h3>
         </div>
        {% empty %}
             <p>Hotel još uvijek nema recenzije.</p>
        {% endfor %}
        </div>   
          </form>
        {% if user.is_staff %}
          <form action="delete_comment" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
          </form>
        {% endif %}

      </div>

    </div>
    {% endblock %}

    
    <script>
        // Add your JavaScript code here
    </script>
</body>
</html>

Hotel booking/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Finder</title>

    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <link rel="icon" href="{% static 'media/logo.jpg' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>


    <div class="container">

        <video autoplay loop muted plays-inline class="back-video">
            <source src="{% static 'novivid.mp4' %}" type="video/mp4">
        </video>

        <div class="navbar" id="navbar">
            <a href="#"  class="active">Početna</a>
            <a href="search">Pretraga</a>
            <a href="login">Log in</a>
            <a href="{%static 'javascript:void(0)'%}" class="icon" onclick="toggleNavbar()">
                <i class="fa fa-bars"></i> 
            </a>
        </div>

        <div class="content">
            <h1>Pronađite pravi hotel za Vas <br>
            Jednostavno nalaženje, jednostavna rezervacija</h1>
            <a class="start-btn" href="search">ZAPOČNITE</a>
        </div>

        <div class="footer">
            <p> &#169; 2023 HotelFinder </p>
        </div>

    </div>

    <script src="../javascript/functions.js"></script>

    <script>
        function toggleNavbar(){
            let navbar = document.querySelector('#navbar');
            if(navbar.className === 'navbar'){
                navbar.className += ' responsive';
                console.log('added')
            }else{
                navbar.className = 'navbar';
            }
        }
    </script>

</body>
</html>

Hotel booking/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">


    <link rel="icon" href="{% static 'media/logo.jpg' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="navbar" id="navbar">
        <a href="index" >Početna</a>
        <a href="search">Pretraga</a>
        <a href="login" class="active">Log in</a>
        <a href="{%static 'javascript:void(0)'%}" class="icon" onclick="toggleNavbar()">
            <i class="fa fa-bars"></i> 
        </a>
    </div>

    <div class="container">
        <div class="form-container">
          <div class="form-content">
            <h2>Prijava</h2>
                {% for message in messages %}
                {{ message }}
                {% endfor %}
                <form action="login" method="POST">
                  {% csrf_token %}
            
                  <div class="fieldset">
                    <label>Email: <input type="email" name="email" required /></label>
                    <label>Sifra: <input type="password" name="password"  required /></label>
                  </div>
                  <input type="submit" value="Potvrdi" />
              
            </form>
          </div>
          <div class="form-content">
            <h2>Registracija</h2>
            <form action="registration" method="POST">
              {% csrf_token %}
              <!-- Registration form fields -->
              <label for="register-username">Korisničko ime:</label>
              <input type="text" id="register-username" name="username">
              <label for="register-password1">Lozinka:</label>
              <input type="password" id="register-password1" name="password1">
              <label for="register-password2">Potvrdi lozinku:</label>
              <input type="password" id="register-password2" name="password2">
              <input type="submit" value="Registriraj se">
            </form>
          </div>
        </div>
      </div>
      
    <div class="footer">
        <p> &#169; 2023 HotelFinder </p>
    </div>
</body>
</html>

Hotel booking/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registracija</title>

    <link rel="stylesheet" href="{% static 'registration.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">


    <link rel="icon" href="{% static 'media/logo.jpg' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="navbar" id="navbar">
        <a href="{% url 'index' %}" class="active">Početna</a>
        <a href="{% url 'search' %}">Pretraga</a>
        <a href="{% url 'login' %}">Log in</a>
        <a href="{%static 'javascript:void(0)'%}" class="icon" onclick="toggleNavbar()">
            <i class="fa fa-bars"></i> 
        </a>
    </div>
    <h1 class="centered">Registracija</h1>
 
    <form action="registration" method="POST">
      {% csrf_token %}
        <label>Unesite ime: <input type="text" name="name" required /></label>
        <label>Unesite prezime: <input type="text" name="surname" required /></label>
        <label>Unesite vas  Email: <input type="email" name="email" required /></label>
        <label>Unesite sifru: <input type="password" name="password"  required /></label>
        <label>Potvrdite sifru: <input type="password" name="confirm_password"  required /></label>
        <label>Unesite korisnicko ime/username: <input type="text" name="username" required /></label>

      <input type="submit" value="Potvrdi" />
    <div class="footer">
        <p> &#169; 2023 HotelFinder </p>
    </div>
</body>
</html>

Hotel booking/templates/reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezervacija</title>

    <link rel="stylesheet" href="{% static 'reservation.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">


    <link rel="icon" href="{% static 'media/logo.jpg' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="navbar" id="navbar">
        <a href="{% url 'index' %}" >Početna</a>
        <a href="{% url 'search' %}">Pretraga</a>
        <a href="{% url 'reservation' %}" class="active">Rezervacija</a>
        <a href="{% url 'registration' %}">Registracija</a>
        <a href="{% url 'login' %}">Log in</a>
        <a href="{%static 'javascript:void(0)'%}" class="icon" onclick="toggleNavbar()">
            <i class="fa fa-bars"></i> 
        </a>
    </div>

    <div class="footer">
        <p> &#169; 2023 HotelFinder </p>
    </div>

</body>
</html>
{% for hotel in hoteli %}
{{hotel}}
{{nase}}
{% endfor %}

Hotel booking/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pretraga</title>

    <link rel="stylesheet" href="{% static 'search.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">


    <link rel="icon" href="{% static 'media/logo.jpg' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;500;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="background-container">
        <div class="background-image"></div>
        <div class="background-layer"></div>
    <div class="navbar" id="navbar">
        <a href="index" >Početna</a>
        <a href="search" class="active">Pretraga</a>
        <a href="login">Log in</a>
        <a href="{%static 'javascript:void(0)'%}" class="icon" onclick="toggleNavbar()">
            <i class="fa fa-bars"></i> 
        </a>
    </div>

    <div class="pretragaime">
        <h1>Pretražite hotel po imenu:</h1> <br>

        <form method="GET" action="{% url 'hotel:search' %}">
            <input type="text" name="ime_query" placeholder="Ime hotela" value="{{ ime_query }}">
            <button type="submit">Pretraga</button>
        </form>
        
        <div id="ime-rezultati-pretrazivanja">
            {% if ime_rezultat %}
                {% for hotel in ime_rezultat %}
                    <div class="rezultat">
                        <a href="{% url 'hotel:hotel_details' hotel.id %}">
                            <div class="image-frame">
                                <img src="{{ hotel.picture.url }}" alt="{{ hotel.ime }}">
                            </div>
                            <h2>{{ hotel.ime }}</h2>
                            <p>{{ hotel.zvjezdice }}  {{hotel.mjesto}}</p>
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                <p>Nema hotela sa ovim imenom .</p>
            {% endif %}
        </div>
    
    </div>
    
    <div class="pretragamjesto">
        <h1>Pretražite hotel po mjestu:</h1>

        <form method="GET" action="{% url 'hotel:search' %}">
            <input type="text" name="mjesto_query" placeholder="ime mjesta" value="{{ mjesto_query }}">
            <button type="submit">Pretraga</button>
        </form>
        
        <div id="mjesto-rezultati-pretrazivanja">
            {% if mjesto_rezultat %}
                {% for hotel in mjesto_rezultat %}
                <div class="rezultat">
                    <a href="{% url 'hotel:hotel_details' hotel.id %}">

                        <div class="image-frame">
                            <img src="{{ hotel.picture.url }}" alt="{{ hotel.ime }}">
                        </div>
                        <h2>{{ hotel.ime }}</h2>
                        <p>{{ hotel.zvjezdice }}  {{ hotel.mjesto }}</p>
                    </a>
                </div>
                {% endfor %}
            {% else %}
                <p>Nema hotela u ovom mjestu</p>
            {% endif %}
        </div>
    </div>

    
</div>   
    <div class="footer">
        <p> &#169; 2023 HotelFinder </p>
    </div>

    <script src="{% static 'search.js' %}"></script>

</body>
</html>